text = input('Enter text to write to the file: ')
file = open(r'C:\Users\panka\Tutedude\Assignment\Assignment_4\output.txt','w',encoding = 'utf-8')
writing_text = file.write(text)
print('Data Successfully written to output.txt')
file.close()
text = input('Enter additional text to append: ')
file = open(r'C:\Users\panka\Tutedude\Assignment\Assignment_4\output.txt','a',encoding = 'utf-8')
appending_text = file.write('\n')
appending_text = file.write(text)
print('Data successfully appended')
file.close()
file = open(r'C:\Users\panka\Tutedude\Assignment\Assignment_4\output.txt','r',encoding = 'utf-8')
reading_text = file.read()
print('Final content of output.txt: ')
print(reading_text)
file.close()
